// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCk24viuidMpVSJrWGMqNC1pcsI3TvmgM',
    appId: '1:1039427063284:web:353305a1f9360e910fbda1',
    messagingSenderId: '1039427063284',
    projectId: 'quraan-dd543',
    authDomain: 'quraan-dd543.firebaseapp.com',
    storageBucket: 'quraan-dd543.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAchR3hvc6n3y3d6LT4Y3QopHLCCHNNwvI',
    appId: '1:1039427063284:android:b982de927def046a0fbda1',
    messagingSenderId: '1039427063284',
    projectId: 'quraan-dd543',
    storageBucket: 'quraan-dd543.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWxtxrD8lnMohGKxWrBwHQkGWrF4PabmI',
    appId: '1:1039427063284:ios:a0f342cb6bec19070fbda1',
    messagingSenderId: '1039427063284',
    projectId: 'quraan-dd543',
    storageBucket: 'quraan-dd543.firebasestorage.app',
    iosBundleId: 'com.nooraliman.quran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWxtxrD8lnMohGKxWrBwHQkGWrF4PabmI',
    appId: '1:1039427063284:ios:a0f342cb6bec19070fbda1',
    messagingSenderId: '1039427063284',
    projectId: 'quraan-dd543',
    storageBucket: 'quraan-dd543.firebasestorage.app',
    iosBundleId: 'com.nooraliman.quran',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCk24viuidMpVSJrWGMqNC1pcsI3TvmgM',
    appId: '1:1039427063284:web:a641f58da50dbcb40fbda1',
    messagingSenderId: '1039427063284',
    projectId: 'quraan-dd543',
    authDomain: 'quraan-dd543.firebaseapp.com',
    storageBucket: 'quraan-dd543.firebasestorage.app',
  );
}
