/// Static list of all 114 Surah names
/// This data is constant and won't change, so we keep it as a static reference
class SurahNames {
  static const List<Map<String, String>> surahs = [
    {'number': '1', 'arabic': 'الفاتحة', 'english': 'Al-Fatiha'},
    {'number': '2', 'arabic': 'البقرة', 'english': 'Al-Baqara'},
    {'number': '3', 'arabic': 'آل عمران', 'english': 'Ali \'Imran'},
    {'number': '4', 'arabic': 'النساء', 'english': 'An-Nisa'},
    {'number': '5', 'arabic': 'المائدة', 'english': 'Al-Ma\'ida'},
    {'number': '6', 'arabic': 'الأنعام', 'english': 'Al-An\'am'},
    {'number': '7', 'arabic': 'الأعراف', 'english': 'Al-A\'raf'},
    {'number': '8', 'arabic': 'الأنفال', 'english': 'Al-Anfal'},
    {'number': '9', 'arabic': 'التوبة', 'english': 'At-Tawba'},
    {'number': '10', 'arabic': 'يونس', 'english': 'Yunus'},
    {'number': '11', 'arabic': 'هود', 'english': 'Hud'},
    {'number': '12', 'arabic': 'يوسف', 'english': 'Yusuf'},
    {'number': '13', 'arabic': 'الرعد', 'english': 'Ar-Ra\'d'},
    {'number': '14', 'arabic': 'إبراهيم', 'english': 'Ibrahim'},
    {'number': '15', 'arabic': 'الحجر', 'english': 'Al-Hijr'},
    {'number': '16', 'arabic': 'النحل', 'english': 'An-Nahl'},
    {'number': '17', 'arabic': 'الإسراء', 'english': 'Al-Isra'},
    {'number': '18', 'arabic': 'الكهف', 'english': 'Al-Kahf'},
    {'number': '19', 'arabic': 'مريم', 'english': 'Maryam'},
    {'number': '20', 'arabic': 'طه', 'english': 'Taha'},
    {'number': '21', 'arabic': 'الأنبياء', 'english': 'Al-Anbya'},
    {'number': '22', 'arabic': 'الحج', 'english': 'Al-Hajj'},
    {'number': '23', 'arabic': 'المؤمنون', 'english': 'Al-Mu\'minun'},
    {'number': '24', 'arabic': 'النور', 'english': 'An-Nur'},
    {'number': '25', 'arabic': 'الفرقان', 'english': 'Al-Furqan'},
    {'number': '26', 'arabic': 'الشعراء', 'english': 'Ash-Shu\'ara'},
    {'number': '27', 'arabic': 'النمل', 'english': 'An-Naml'},
    {'number': '28', 'arabic': 'القصص', 'english': 'Al-Qasas'},
    {'number': '29', 'arabic': 'العنكبوت', 'english': 'Al-\'Ankabut'},
    {'number': '30', 'arabic': 'الروم', 'english': 'Ar-Rum'},
    {'number': '31', 'arabic': 'لقمان', 'english': 'Luqman'},
    {'number': '32', 'arabic': 'السجدة', 'english': 'As-Sajda'},
    {'number': '33', 'arabic': 'الأحزاب', 'english': 'Al-Ahzab'},
    {'number': '34', 'arabic': 'سبأ', 'english': 'Saba'},
    {'number': '35', 'arabic': 'فاطر', 'english': 'Fatir'},
    {'number': '36', 'arabic': 'يس', 'english': 'Ya-Sin'},
    {'number': '37', 'arabic': 'الصافات', 'english': 'As-Saffat'},
    {'number': '38', 'arabic': 'ص', 'english': 'Sad'},
    {'number': '39', 'arabic': 'الزمر', 'english': 'Az-Zumar'},
    {'number': '40', 'arabic': 'غافر', 'english': 'Ghafir'},
    {'number': '41', 'arabic': 'فصلت', 'english': 'Fussilat'},
    {'number': '42', 'arabic': 'الشورى', 'english': 'Ash-Shuraa'},
    {'number': '43', 'arabic': 'الزخرف', 'english': 'Az-Zukhruf'},
    {'number': '44', 'arabic': 'الدخان', 'english': 'Ad-Dukhan'},
    {'number': '45', 'arabic': 'الجاثية', 'english': 'Al-Jathiya'},
    {'number': '46', 'arabic': 'الأحقاف', 'english': 'Al-Ahqaf'},
    {'number': '47', 'arabic': 'محمد', 'english': 'Muhammad'},
    {'number': '48', 'arabic': 'الفتح', 'english': 'Al-Fath'},
    {'number': '49', 'arabic': 'الحجرات', 'english': 'Al-Hujurat'},
    {'number': '50', 'arabic': 'ق', 'english': 'Qaf'},
    {'number': '51', 'arabic': 'الذاريات', 'english': 'Adh-Dhariyat'},
    {'number': '52', 'arabic': 'الطور', 'english': 'At-Tur'},
    {'number': '53', 'arabic': 'النجم', 'english': 'An-Najm'},
    {'number': '54', 'arabic': 'القمر', 'english': 'Al-Qamar'},
    {'number': '55', 'arabic': 'الرحمن', 'english': 'Ar-Rahman'},
    {'number': '56', 'arabic': 'الواقعة', 'english': 'Al-Waqi\'a'},
    {'number': '57', 'arabic': 'الحديد', 'english': 'Al-Hadid'},
    {'number': '58', 'arabic': 'المجادلة', 'english': 'Al-Mujadila'},
    {'number': '59', 'arabic': 'الحشر', 'english': 'Al-Hashr'},
    {'number': '60', 'arabic': 'الممتحنة', 'english': 'Al-Mumtahina'},
    {'number': '61', 'arabic': 'الصف', 'english': 'As-Saf'},
    {'number': '62', 'arabic': 'الجمعة', 'english': 'Al-Jumu\'a'},
    {'number': '63', 'arabic': 'المنافقون', 'english': 'Al-Munafiqun'},
    {'number': '64', 'arabic': 'التغابن', 'english': 'At-Taghabun'},
    {'number': '65', 'arabic': 'الطلاق', 'english': 'At-Talaq'},
    {'number': '66', 'arabic': 'التحريم', 'english': 'At-Tahrim'},
    {'number': '67', 'arabic': 'الملك', 'english': 'Al-Mulk'},
    {'number': '68', 'arabic': 'القلم', 'english': 'Al-Qalam'},
    {'number': '69', 'arabic': 'الحاقة', 'english': 'Al-Haaqqa'},
    {'number': '70', 'arabic': 'المعارج', 'english': 'Al-Ma\'arij'},
    {'number': '71', 'arabic': 'نوح', 'english': 'Nuh'},
    {'number': '72', 'arabic': 'الجن', 'english': 'Al-Jinn'},
    {'number': '73', 'arabic': 'المزمل', 'english': 'Al-Muzzammil'},
    {'number': '74', 'arabic': 'المدثر', 'english': 'Al-Muddaththir'},
    {'number': '75', 'arabic': 'القيامة', 'english': 'Al-Qiyama'},
    {'number': '76', 'arabic': 'الإنسان', 'english': 'Al-Insan'},
    {'number': '77', 'arabic': 'المرسلات', 'english': 'Al-Mursalat'},
    {'number': '78', 'arabic': 'النبأ', 'english': 'An-Naba'},
    {'number': '79', 'arabic': 'النازعات', 'english': 'An-Nazi\'at'},
    {'number': '80', 'arabic': 'عبس', 'english': 'Abasa'},
    {'number': '81', 'arabic': 'التكوير', 'english': 'At-Takwir'},
    {'number': '82', 'arabic': 'الإنفطار', 'english': 'Al-Infitar'},
    {'number': '83', 'arabic': 'المطففين', 'english': 'Al-Mutaffifin'},
    {'number': '84', 'arabic': 'الإنشقاق', 'english': 'Al-Inshiqaq'},
    {'number': '85', 'arabic': 'البروج', 'english': 'Al-Buruj'},
    {'number': '86', 'arabic': 'الطارق', 'english': 'At-Tariq'},
    {'number': '87', 'arabic': 'الأعلى', 'english': 'Al-A\'la'},
    {'number': '88', 'arabic': 'الغاشية', 'english': 'Al-Ghashiya'},
    {'number': '89', 'arabic': 'الفجر', 'english': 'Al-Fajr'},
    {'number': '90', 'arabic': 'البلد', 'english': 'Al-Balad'},
    {'number': '91', 'arabic': 'الشمس', 'english': 'Ash-Shams'},
    {'number': '92', 'arabic': 'الليل', 'english': 'Al-Layl'},
    {'number': '93', 'arabic': 'الضحى', 'english': 'Ad-Duhaa'},
    {'number': '94', 'arabic': 'الشرح', 'english': 'Ash-Sharh'},
    {'number': '95', 'arabic': 'التين', 'english': 'At-Tin'},
    {'number': '96', 'arabic': 'العلق', 'english': 'Al-Alaq'},
    {'number': '97', 'arabic': 'القدر', 'english': 'Al-Qadr'},
    {'number': '98', 'arabic': 'البينة', 'english': 'Al-Bayyina'},
    {'number': '99', 'arabic': 'الزلزلة', 'english': 'Az-Zalzala'},
    {'number': '100', 'arabic': 'العاديات', 'english': 'Al-Adiyat'},
    {'number': '101', 'arabic': 'القارعة', 'english': 'Al-Qari\'a'},
    {'number': '102', 'arabic': 'التكاثر', 'english': 'At-Takathur'},
    {'number': '103', 'arabic': 'العصر', 'english': 'Al-Asr'},
    {'number': '104', 'arabic': 'الهمزة', 'english': 'Al-Humaza'},
    {'number': '105', 'arabic': 'الفيل', 'english': 'Al-Fil'},
    {'number': '106', 'arabic': 'قريش', 'english': 'Quraysh'},
    {'number': '107', 'arabic': 'الماعون', 'english': 'Al-Ma\'un'},
    {'number': '108', 'arabic': 'الكوثر', 'english': 'Al-Kawthar'},
    {'number': '109', 'arabic': 'الكافرون', 'english': 'Al-Kafirun'},
    {'number': '110', 'arabic': 'النصر', 'english': 'An-Nasr'},
    {'number': '111', 'arabic': 'المسد', 'english': 'Al-Masad'},
    {'number': '112', 'arabic': 'الإخلاص', 'english': 'Al-Ikhlas'},
    {'number': '113', 'arabic': 'الفلق', 'english': 'Al-Falaq'},
    {'number': '114', 'arabic': 'الناس', 'english': 'An-Nas'},
  ];

  /// Get surah name by number (1-114)
  /// Returns empty string if invalid number
  static String getArabicName(int surahNumber) {
    if (surahNumber < 1 || surahNumber > 114) return '';
    return surahs[surahNumber - 1]['arabic']!;
  }

  /// Get English surah name by number (1-114)
  /// Returns empty string if invalid number
  static String getEnglishName(int surahNumber) {
    if (surahNumber < 1 || surahNumber > 114) return '';
    return surahs[surahNumber - 1]['english']!;
  }

  /// Get surah name (Arabic or English) based on UI language
  static String getName(int surahNumber, bool isArabic) {
    return isArabic ? getArabicName(surahNumber) : getEnglishName(surahNumber);
  }
}
